name: ecommerce_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  carousel_slider: ^5.1.1
  dartz: ^0.10.1
  dio: ^5.9.0
  equatable: ^2.0.7
  flex_color_scheme: ^8.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.1
  freezed_annotation: ^3.1.0
  go_router: ^16.3.0
  google_fonts: ^6.3.2
  hydrated_bloc: ^10.1.1
  json_annotation: ^4.9.0
  keyboard_dismisser: ^3.0.0
  path_provider: ^2.1.5
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.10.1
  freezed: ^3.2.3
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true

  assets:
    - images/
    - icons/

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter_24pt-Regular.ttf
        - asset: fonts/Inter_24pt-Thin.ttf
          weight: 100
        - asset: fonts/Inter_24pt-ExtraLight.ttf
          weight: 200
        - asset: fonts/Inter_24pt-Light.ttf
          weight: 300
        - asset: fonts/Inter_24pt-Medium.ttf
          weight: 500
        - asset: fonts/Inter_24pt-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter_24pt-Bold.ttf
          weight: 700
        - asset: fonts/Inter_24pt-ExtraBold.ttf
          weight: 800
        - asset: fonts/Inter_24pt-Black.ttf
          weight: 900
